### ISSUE TITLE
HC-SR04 - Distance Measurement incorrect

### ISSUE THREAD

**Issue by kabongsteve** [obniz/obniz#70]
I have been using this component and found it only ever measured upto ~60mm and rarely changed.

Through debugging and investigation, I found the length of time between power on and trigger seems to be too short, or it needs to be permanently powered.

I moved the power on into the wired function (permanent power) and don't turn off in the callback function and now I get more accurate and continuous results.

Other implementations I have seen support multiple samples with averaging to get a better distance result.

Something like that would also be useful.

thanks

**Comment by yuki-sato** [comment]
Hi @kabongsteve 

Thank you for the posting issue.

I will investigate this. Maybe I will add delay between power on and trigger.

The reason obniz library HC-SR04 power up-down on each measurement is Old version of HC-SR04 has problem in measurement management.
It require power reset every time.
So We decided reset component at every time.

But this is inconvenient for almost HC-SR04 users.
We will discuss about this and will make a decision in a few days and also will fix it.

Thank you.

**Comment by yuki-sato** [comment]
Hi @kabongsteve 

We updated obniz.js 
[https://github.com/obniz/obniz/releases/tag/v1.3.1](https://github.com/obniz/obniz/releases/tag/v1.3.1)

HC-SR04 was updated.
It power will be supplied continuously.
And temperature revise property was added.

Multiple sampling and averaging was not added.
But we added measureWait() method
[https://obniz.io/sdk/parts/HC-SR04/README.md?iframe=false](https://obniz.io/sdk/parts/HC-SR04/README.md?iframe=false)
It make easy to write multiple measuring code.

Thanks

**Comment by kabongsteve** [comment]
Hi guys,

Updated to latest version and run my code again.

All working extremely well, including more reliably and faster.

Great work
thanks
