### ISSUE TITLE
Feature Request: Support for 74C595A Serial to Parallel Register

### ISSUE THREAD

**Issue by kabongsteve** [obniz/obniz#73]
I was wondering if you could add support for the 74HC595A Serial Shift Register.
https://www.onsemi.com/pub/Collateral/MC74HC595A-D.PDF

I currently use these chips to expand the number of outputs available.
Normally only need to use Data/Latch/Clock, but Output Enable also useful to make sure all outputs off when first powered on and setup.

**Comment by 9wick** [comment]
OK, we will try it.

**Comment by yuki-sato** [comment]
@kabongsteve Hi!

Now obniz.js v1.4.0 was released.
And it includes [SNx4HC595](https://obniz.io/sdk/parts/SNx4HC595).
We believe MC74HC595A will works with this library.

**Comment by kabongsteve** [comment]
Hi yuki-sato, 9wick,

The one I have, is wired up to an 8 Relay Module, which I believe is active low to turn on relays.
I have OE connected, so I can have all OFF, until configured and set.

I have given it a quick try with the examples on the document parts and only partial success.

 By including oe, and calling setEnable(true), I get all relays turning on and indicator led's lighting up.
But any calls to output, with true or false, don't seem to be changing the individual relays.

I will have another play soon, rechecking my wiring and coding in node.js to further investigate.

**Comment by yuki-sato** [comment]
Hi @kabongsteve 

Without calling setEnable(), does obniz can control any of SNx4HC595's output?

Shifting seems not working correctly. Are rclk and srclk connected to right pin?

**Comment by kabongsteve** [comment]
I'm still having no luck getting the driver to work.

I have loaded a Test 74xHC595.js script to my repository.

Within this script I have a raw() function that works and sets the correct outputs for my chip and relay board.
My understanding is that this should be the exact same result as using the chip() function.
Running the chip() function always gives me all low values (all relays on)
NOTE: I run under node.js on a Windows PC.

Could you test at your end and let me know any issues.

Secondly, In your logic/SNx4HC595/index.js I would like to suggest the following:
1) the srclk and rclk should be set to high on initialization, as pulsing low operates the chip (lines 29,30)
2) the ser could be set prior to the high/low transition of the srclk, giving it more time to be stable before inverse low/high transition.
3) not sure why the flush has the array variable and operation.  is this a variant on timing?

**Comment by yuki-sato** [comment]
@kabongsteve Thank you for investigation.

I will test with your script. And check our source with your suggestion.

**Comment by kabongsteve** [comment]
@yuki-sato 
I keep getting "TypeError: _parts[name] is not a constructor" message when I try to use the above beta code.
Can you give me complete sample script for how to do this under node.js.

but separately SUCCESS.
By modifying the 1.4.3 code version and moving the setVccGnd to after the settings of the io_sr, io_srclk and io_rclk I get it to work as expected.
ie
...
    this.io_ser.output(false);
    this.io_srclk.output(false);
    this.io_rclk.output(false);

    this.obniz.setVccGnd(this.params.vcc, this.params.gnd, '5v');
...
I do not need to have the triple outputs in the flush function, the 1.4.3 single calls work successfully.
thanks
Steve

**Comment by yuki-sato** [comment]
@kabongsteve Oh, Sorry, i forgot you are using node.js. my code was for html.

But you succeeded by moving setVccGnd method to after.
We will include this next release.

Thank you!

**Comment by kabongsteve** [comment]
@yuki-sato 
You said you would include my fix in the next release
(Moving the setVccGnd method to after the other outputs.

You don't seem to have made this change

**Comment by yuki-sato** [comment]
@kabongsteve 

I included some of your suggestion. But I hesitated "Moving the setVccGnd method".
Because If srclr was configured, then srclr was initially set to "5v" before Vcc/Gnd supplied.
It may damage a chip.
And You fixed yourself. So I thought you don't need this and I committed without this.

But you have waited my release. I'm sorry for that.
I update parts version 1.5.2 which has option "power_delay".
By default, it is false. Vcc/Gnd supply before each outputs.
Please specify to 'true'. Vcc/Gnd will supply after each outputs.

See more details on [document](https://obniz.io/sdk/parts/SNx4HC595/README.md?iframe=false)

I should have asked to you before I close this issue.

**Comment by kabongsteve** [comment]
@yuki-sato 
Interesting update.
In reviewing the specs of the chip, I see all other inputs irrelevant for the SRCLR input, perhaps this can be simplified.

Since the 3 other inputs are all initialezed to low, it doesn't matter where power is on or not.
So i re coded to the following:-

    this.io_ser = this.obniz.getIO(this.params.ser);
    this.io_srclk = this.obniz.getIO(this.params.srclk);
    this.io_rclk = this.obniz.getIO(this.params.rclk);

    this.io_ser.output(false);
    this.io_srclk.output(false);
    this.io_rclk.output(false);

    this.obniz.setVccGnd(this.params.vcc, this.params.gnd, '5v');

    if (this.obniz.isValidIO(this.params.srclr)) {
      this.io_srclr = this.obniz.getIO(this.params.srclr);
      this.io_srclr.output(true);
    }

And this works successfully, and I assume would for you as well, even with srclr used.

Steve

**Comment by yuki-sato** [comment]
@kabongsteve Hi
That's good news! Because I wanted to move srclr to after vcc/gnd.
But I worried this affect bad for your environment.

I released obniz.js 1.6.0. It include this change.
Please review it.

**Comment by kabongsteve** [comment]
@yuki-sato 
Hi,  I have to apologize, as I have found my issue and it had nothing to do with the code.
I had the SRCLR floating (pin 10) so I an amazed I ever got anything to work.  
Now I have it pulled hi, it works perfectly.

2 minor suggestions.  
1) when OE is specified, you currently set it high, but then the end of the wired() function you set it low.  Thus when configured, it defaults to low or Enabled.  The reason I asked for it to be added, was so they could be disabled, until the setEnable is called.  that way, I can set all outputs as wanted (in my case all high) before enabling the outputs.
If we can remove the final this.io_oe.output(false) then this will work as required.
2) in the setEnable function you have
if (!this.io_oe && enable == false) 
I believe the && enable == false shouldn't be there at all.  
If I call setEnable(true) without defining OE, then an exception is thrown.

thanks
Steve

**Comment by yuki-sato** [comment]
@kabongsteve It's OK! working perfectly is better. I was wondering why there are difference.

I deployed obniz.js 1.7.1
It include new wired property "enabled". you can opt out  final this.io_oe.output(false) with supplying enabled:false. See more detail on document.

```if (!this.io_oe && enable == false)``` is to show more user friendly error message.
Without this, It will throw error because io_oe doesn't exist.
But the error message is not friendly.
So I'm manually handling it.

Thank you.

**Comment by yuki-sato** [comment]
@kabongsteve Hello.

We are moving issue tracking to our forum.

We copied title of this thread and last comments to the forum.

[https://forum.obniz.io/topic/17/support-for-74c595a-serial-to-parallel-register](https://forum.obniz.io/topic/17/support-for-74c595a-serial-to-parallel-register)

We are closing issue tracking on GitHub in few days.
So, Please visit the forum and post any comments on it.

Best Regards.

**Comment by kabongsteve** [comment]
thanks,

My comment on Jul 8th stated that I had gotten it working, and had some other suggestions.

But basically its completed and can be closed

**Comment by yuki-sato** [comment]
@kabongsteve Thank you!
